name: ween
favicon: null
layout_spectrum: 0.5522305446211249
typography_spectrum: 0.49120472418144345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.41001774254254997
  lightness: 0.501165974419564
  saturation: 0.02161853015422821
  rhythmicContrast: 0.702093388652429
purpose: []
