name: ween
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49120472418144345
title: Prepare the mount boy...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#ffffff'
    - '#d0d0d0'
    - '#434343'
    - '#9f9f9f'
  brandStrength: 0.41001774254254997
  lightness: 0.501165974419564
  saturation: 0.02161853015422821
  rhythmicContrast: 0.702093388652429
purpose: []
